# Generated by Django 4.0.3 on 2022-04-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answeer',
            new_name='answer',
        ),
    ]
